import type { Metadata } from "next";
import { ThemeProvider } from "../context/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body style={{
          margin: 0,
          padding: 0,        
        }}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
