import { Box } from '@mui/material';
import Sidebar from '../components/layout/sidebar';
import { ThemeProvider } from '@palico-ai/components';
import './global.css';

export const metadata = {
  title: 'Welcome to studio',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Box sx={{ display: 'flex', backgroundColor: 'background.default' }}>
            <Sidebar />
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
