import { Box } from '@mui/material';
import Topbar from '../components/layout/topbar';
import Sidebar from '../components/layout/sidebar';
import { ThemeProvider } from '@palico-ai/components';
import './global.css';

export const metadata = {
  title: 'Welcome to studio',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Box sx={{ display: 'flex', backgroundColor: 'background.default' }}>
            <Sidebar />
            <Box
              sx={{
                flexGrow: 1,
                display: 'flex',
                flexDirection: 'column',
                height: '100vh',
              }}
            >
              <Topbar />
              <Box
                sx={{
                  flex: 1,
                  overflow: 'auto',
                }}
              >
                {children}
              </Box>
            </Box>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
