export enum ENVName {
  // SHARED
  DEV_MODE = 'DEV_MODE',
  JWT_SECRET = 'JWT_SECRET',
  // USED BY PALICO APP
  PALICO_API_PORT = 'PUBLIC_API_PORT',
  PALICO_API_DATABASE_URL = 'DATABASE_URL',
  // USED BY PALICO STUDIO
  PALICO_STUDIO_API_URL = 'PALICO_API_URL',
  PALICO_STUDIO_API_SERVICE_KEY = 'PALICO_API_SERVICE_KEY',
  STUDIO_USERNAME = 'STUDIO_USERNAME',
  STUDIO_PASSWORD = 'STUDIO_PASSWORD',
  // USED BY DOCKER-COMPOSE
  DOCKER_COMPOSE_DB_USERNAME = 'DOCKER_COMPOSE_DATABASE_USERNAME',
  DOCKER_COMPOSE_DB_PASSWORD = 'DOCKER_COMPOSE_DATABASE_PASSWORD',
  DOCKER_COMPOSE_DATABASE_NAME = 'DOCKER_COMPOSE_DATABASE_NAME',
  DOCKER_COMPOSE_DB_PORT = 'DOCKER_COMPOSE_DATABASE_PORT',
  DOCKER_COMPOSE_STUDIO_PORT = 'DOCKER_COMPOSE_STUDIO_PORT',
  DOCKER_COMPOSE_API_PORT = 'DOCKER_COMPOSE_API_PORT',
  DOCKER_COMPOSE_SERVICE_KEY = 'DOCKER_COMPOSE_SERVICE_KEY',
  DOCKER_COMPOSE_STUDIO_USERNAME = 'DOCKER_COMPOSE_STUDIO_USERNAME',
  DOCKER_COMPOSE_STUDIO_PASSWORD = 'DOCKER_COMPOSE_STUDIO_PASSWORD',
  DOCKER_COMPOSE_JWT_SECRET = 'DOCKER_COMPOSE_JWT_SECRET',
}

export const getEnvOrThrow = (name: ENVName): string => {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} is not set`);
  }
  return value;
};
